<?php

namespace app\admin\controller;

use think\Db;

class Nav extends Base
{
    //模型table
    private static $_model = 'model';
    //栏目table
    private static $_category = 'category';


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //获取已定义模型
        $model = Db::name(self::$_model)->field('id,name')->select();
        //已添加栏目
        $category = getAllCategory('all');
        $this->assign('model', $model);
        $this->assign('category', $category["data"]);
    }

    //导航页
    function index()
    {
        if(request()->isAjax()){
            $param = input('param.');
            $limit = $param['pageSize'];
            $offset = ($param['pageNumber'] - 1) * $limit;
            $where = [];
            if (isset($param['searchText']) && !empty($param['searchText'])) {
                $where['name'] = ['like', '%' . $param['searchText'] . '%'];
            }
            $category = getAllCategory('all','',$offset.",".$limit,$where);
            $data = create_tree_dom($category["data"]);
            $return['total'] = $category["total"];
            $return['rows'] = $data;

            return json($return);
         }
         
         return $this->fetch();
    }

    //添加导航UI
    function add()
    {
        if(request()->isPost()){

            $param = input('param.');
            $param = parseParams($param['data']);
            $flag = get_system_value('site_editor');
            $data['flag'] = $flag == 'markdown'?1:0;
            //新增导航
            $flag = Db::name(self::$_category)->insert($param);
            if ($flag) {
                  return json(['code' => 1, 'data' => ["url"=>url('nav/index'),'type' => 'nav'], 'msg' => "添加栏目成功"]);
            
              }else{
                  return json(['code' => 0, 'data' => ["url"=>url('nav/index'),'type' => 'nav'], 'msg' => "添加栏目失败"]);                  
              }
        }
        return $this->fetch();
    }

    /*
     * 编辑导航
     */
    public function edit(){
        if (request()->isPost()) {
            $param = input('post.');
            $data = parseParams($param['data']);
            $id = $data['id'];
            unset($data['id']);
            $flag = get_system_value('site_editor');
            $data['flag'] = $flag == 'markdown'?1:0;
            $flag = Db::name(self::$_category)->where(['id' => $id])->update($data);
            if ($flag !== false) {
                return json(['code' => 1, 'data' => ["url"=>url('nav/index'),'type' => 'nav'], 'msg' => "修改栏目成功"]);
          
            }else{
                return json(['code' => 0, 'data' => ["url"=>url('nav/index'),'type' => 'nav'], 'msg' => "修改栏目失败"]);                  
            }
        } else {
            $id = input('param.id/d',0);
            $data = Db::name(self::$_category)->where(['id' => $id])->find();
            $this->assign('data',$data);
            return $this->fetch();
        }
        
    }

    /*
     * 删除导航
     */
    public function dele(){
        $id = input('param.id/d',0);
        $flag = Db::name(self::$_category)->where(['id' => $id])->delete();
        if ($flag!== false) {
            return json(['code' => 1,  'msg' => "删除成功"]);
      
        }else{
            return json(['code' => 0, 'msg' => "删除失败"]);                  
        }
    }
}
